version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      npm-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: gomod
    directory: /tokenpulse-server
    schedule: { interval: weekly }
    groups:
      go-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /tokenpulse-server
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /tokenpulse-web
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /deploy
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
